// +build windows

package nagiosfoundation

import (
	"flag"
	"fmt"
	"log"
	"os"

	"github.com/jkerry/nagiosfoundation/lib/pkg/cpu"
	"github.com/jkerry/nagiosfoundation/lib/pkg/nagiosformatters"
)

func CheckCPU() {
	var warning = flag.Float64("warning", 85, "the average cpu threshold to issue a warning alert")
	var critical = flag.Float64("critical", 95, "the average cpu threshold to issue a critical alert")
	var metricName = flag.String("metric_name", "pct_processor_time", "the name of the metric generated by this check")
	flag.Parse()
	value, err := cpu.GetCPULoad()
	if err == nil {
		var msg string
		var retcode int
		msg, retcode = nagiosformatters.GreaterFormatNagiosCheck("\\Processor(_Total)\\% Processor Time", value, *warning, *critical, *metricName)
		fmt.Println(msg)
		os.Exit(retcode)
	} else {
		log.Println(err)
		os.Exit(3)
	}
}
