package cmd

import (
	"fmt"
	"os"

	"github.com/ncr-devops-platform/nagiosfoundation/cmd/initcmd"
	"github.com/ncr-devops-platform/nagiosfoundation/lib/app/nagiosfoundation"
	"github.com/spf13/cobra"
)

// Execute runs the root command
func Execute() {
	var warning, critical int
	var metricName string

	var rootCmd = &cobra.Command{
		Use:   "check_cpu",
		Short: "Check the CPU usage.",
		Long: `Perform a CPU check by getting the usage percentage and if
above --critical percentage, issue a CRITICAL response, else if it is
above --warning percentage, issue a WARNING response. If it's below both
of these, an OK response is issued.`,
		Run: func(cmd *cobra.Command, args []string) {
			cmd.ParseFlags(os.Args)
			msg, retval := nagiosfoundation.CheckCPU(warning, critical, metricName)

			fmt.Println(msg)
			os.Exit(retval)
		},
	}

	initcmd.AddVersionCommand(rootCmd)

	rootCmd.Flags().IntVarP(&warning, "warning", "w", 85, "the average cpu threshold to issue a warning alert")
	rootCmd.Flags().IntVarP(&critical, "critical", "c", 95, "the average cpu threshold to issue a critical alert")
	rootCmd.Flags().StringVarP(&metricName, "metric_name", "m", "pct_processor_time", "the name of the metric generated by this check")

	if err := rootCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
